# Generated by Django 3.2.5 on 2021-07-25 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('email', models.CharField(max_length=25)),
                ('message', models.TextField()),
            ],
        ),
    ]
