# Generated by Django 3.2.5 on 2021-07-26 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_contact_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
