# Generated by Django 3.2.5 on 2021-07-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210730_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Todo',
        ),
    ]
